server:
  port: 8081

spring:
  application:
    name: service-b
  zipkin:
    sender:
      type: kafka
  kafka:
    bootstrap-servers: localhost:19092

logging:
  level:
    root: INFO
#    org.apache.coyote.http11.Http11InputBuffer: DEBUG