server:
  port: 8080

spring:
  application:
    name: service-a
  zipkin:
    sender:
      type: kafka
  kafka:
    bootstrap-servers: localhost:19092

logging:
  level:
    root: INFO
#    sun.net.www.protocol.http.HttpURLConnection: DEBUG
